from .index_structure.rtree import RTree

SKIP_IN_PATH = (None, '', b'', [], ())
# TODO: INDEX_STRUCTURE_MAPPER should be generated by a function e.g: get indexes
INDEX_STRUCTURE_MAPPER = {'rtree': RTree}
DOC_TYPE_ANALYZER = {'xml': None, 'json': None, 'csv': None}
